# Generated by Django 5.2.4 on 2026-02-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customers_created_at_customers_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
