# Generated by Django 5.2.4 on 2025-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('age', models.DecimalField(decimal_places=2, max_digits=99)),
                ('gender', models.TextField()),
                ('country', models.TextField(max_length=900)),
            ],
        ),
    ]
