# Generated by Django 5.2.4 on 2026-02-11 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
